---
services:
  redmine:
    container_name: redmine
    image: redmica/redmica
    hostname: redmine-main
    restart: always
    environment:
      - "REDMINE_DB_MYSQL=${REDMINE_DB_MYSQL}"
      - "REDMINE_DB_USERNAME=${REDMINE_DB_USERNAME}"
      - "REDMINE_DB_PASSWORD=${REDMINE_DB_PASSWORD}"
      - "REDMINE_SECRET_KEY_BASE=${REDMINE_SECRET_KEY_BASE}"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: "docker.{{.Name}}"
        fluentd-async-connect: "true"
    ports:
      - "0.0.0.0:8000:3000"
    volumes:
      - ./redmine/data:/usr/src/redmine/files/
      - ./redmine/plugins:/usr/src/redmine/plugins/
    depends_on:
      - mysql
    networks:
      - redmine_nw
      - fluent_nw

  mysql:
    container_name: mysql
    image: mysql:5.7
    hostname: redmine-mysql
    restart: always
    shm_size: 128mb
    environment:
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: "docker.{{.Name}}"
        fluentd-async-connect: "true"
    volumes:
      - ./postgres/data:/data
    depends_on:
      - fluentd
    networks:
      - redmine_nw
      - fluent_nw
      
  adminer:
    container_name: adminer
    image: adminer
    hostname: redmine-adminer
    restart: always
    ports:
      - "0.0.0.0:8080:8080"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: "docker.{{.Name}}"
        fluentd-async-connect: "true"
    depends_on:
      - mysql
    networks:
      - redmine_nw
      - fluent_nw
      
  fluentd:
    container_name: fluentd
    image: fluentd:v1.16.2-debian-1.1
    hostname: redmine-fluentd
    restart: always
    ports:
      - "0.0.0.0:24224:24224"
      - "0.0.0.0:24224:24224/udp"
    environment:
      - FLUENTD_CONF=fluent.conf
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
      - ./fluentd/etc:/fluentd/etc/
      - ./fluentd/log:/fluentd/log
    networks:
      - fluent_nw
      
networks:
  redmine_nw:
    internal: false
  fluent_nw:
    internal: true
